eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1101/eureka/
server:
  port: 1111
spring:
  application:
    name: feign_server

feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE